{% set name = "caniusepython3" %}
{% set version = "7.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58cb3b3643530bc955d3dc5fe49385ccd1f0d2677bf1d9b159814c0f5e677562

build:
  noarch: python
  number: 0
  entry_points:
    - caniusepython3 = caniusepython3.__main__:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - distlib
    - packaging
    - python >=3.6
    - requests

test:
  imports:
    - caniusepython3
  commands:
    - caniusepython3 --help

about:
  home: https://github.com/brettcannon/caniusepython3
  license: Apache-2.0
  license_file: LICENSE
  summary: Determine what projects are blocking you from porting to Python 3
  doc_url: https://github.com/brettcannon/caniusepython3/blob/master/README.md
  dev_url: https://github.com/brettcannon/caniusepython3

extra:
  recipe-maintainers:
    - chrisburr
